#Gui配置
#只需要往里面添加物品就好了，不需要设计的像ChestCommand一样，物品自动从上往下排序
#Gui的边框和个人信息已经设置完毕了！
Gui:
  #名字
  1MCoin:
    #物品材质（必须）
    Material: sunflower
    #物品名称（非必须）
    Name: '&e1,000,000金币'
    #物品描述（非必须）
    Lore:
    - '&f点击购买1,000,000金币'
    - '&a价格 &7>> &65 &d活动代币'
    #需要的活动代币数量（必须，且必须为正）
    Price: 5
    #支付后执行的指令（必须，控制台执行，可以添加多条）
    #可用变量：%player% - 玩家
    Action:
    - 'eco give %player% 1000000'
    #附魔，可添加多个（非必须）
    Enchantments:
    - 'durability,1'